on:
  schedule:
    cron: '0 11 * * *'

jobs:
  daily-update:
    runs-on: macos-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::jsonlite
            any::stringr
            any::lubridate
            any::bpr

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run script
        run: Rscript -e 'source("Daily_script.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Daily Update' 
          git push origin main
