on:
  schedule:
    - cron: '30 10 * * *'
permissions:
  contents: write
jobs:
  daily-update:
    runs-on: macos-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::httr
            any::jsonlite
            any::stringr
            any::lubridate
            any::bpr

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run script
        run: Rscript -e 'source("Ratings_Update.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Daily Ratings Update' 
          git push origin main
